"""
Make10 遊戲自動化系統 - 遊戲常數定義
包含基本的遊戲規則和系統常數
"""

# 圖像處理常數
CELL_SIZE = (28, 28)
BOARD_SIZE = (10, 25)

# 圖像預處理常數
CANNY_THRESHOLD1 = 50
CANNY_THRESHOLD2 = 150

# 霍夫直線檢測常數
HOUGH_RHO = 1
HOUGH_THETA_RESOLUTION = 180
HOUGH_THRESHOLD = 100
HOUGH_MIN_LINE_LENGTH = 50
HOUGH_MAX_LINE_GAP = 10

# AI 模型常數
MODEL_BATCH_SIZE = 32
MODEL_CONFIDENCE_THRESHOLD = 0.7
MODEL_VOTING_THRESHOLD = 0.8

# 自動化控制常數
CLICK_DELAY = 0.1
DRAG_DELAY = 0.2
SCREEN_SWITCH_DELAY = 0.1
SCREENSHOT_DELAY = 0.3
RETRY_ATTEMPTS = 3
AUTOMATION_TIMEOUT = 30

# 遊戲檢測常數
TEMPLATE_MATCH_THRESHOLD = 0.8
